### ISSUE TITLE
Combine 을 쓰지 않고 델리게이트를 사용한 이유가 있을까요?

### ISSUE THREAD

**Issue by x-0o0** [insub4067/SwiftUIViewModel-Command#1]
likeOffsetPublisher 같은 퍼블리셔 하나 두고
Detail에서 `likeOffsetPublisher.send(offset)`
Parent에서 `.receive(likeOffsetPublisher)`

를 사용하는 방식으로 한다면 깔끔하게 할 수 있지 않을까 생각이 들었는데요,
Combine을 활용하지 않고 delegate 방식을 사용한 이유나 의견이 궁금합니다!

**Comment by insub4067** [comment]
@jaesung-0o0 

답변이 늦었습니다 ! 
사실 이 레포는 디자인 패턴 책 읽으면서 디자인 패턴을 Swift 프로젝트에서 간단하게 나마 한번씩 써보자의 의미를 두고 만든 거라 Combine 을 써볼 생각을 못했지만 그 역시 좋은 아이디어 같습니다 ~! 😅

**Comment by insub4067** [comment]
@jaesung-0o0  
TMI.. 새로오신 모바일 팀장님이 내주신 숙제중 일부였답니다. 😂

**Comment by insub4067** [comment]
@jaesung-0o0 
혹시 말씀하신 형태가 아래와 같은 형태 맞을 까요? 👀
https://github.com/insub4067/CombinePublisher

**Comment by x-0o0** [comment]
네 맞습니다🙂

퍼블리셔 객체를 상위뷰가 들고 있고 이벤트 퍼블리싱을 하위뷰에서 하는게 단방향 느낌이 아니라서 아래처럼 바꾸면 어떨까요? 의견 주시면 감사하겠습니다.

## 제안
```swift
class DetailDataModel: ObservableObject {
    static let likeStatusPublisher = PassthroughSubject<(Int, Bool), Never>

    func toggleLikeStatus() {
        self.item.isLiked.toggle()
        Self.likeStatusPublisher.send((offset, item.isLiked)
    }
}
```

```swift
// DetailView
@StateObject var dataModel: DetailDataModel

init(item: Item, offset: Int) {
    // Create model data instance
}

var body: some View {
    Button {
        dataModel.toggleLikeStatus()
    } label: {
        LikeImage()
    }
}
```
```
// ParentView
.onReceive(DetailDataModel.likeStatusPublisher) { offset, liked in
    // handle received values
}
```

**Comment by insub4067** [comment]
@jaesung-0o0 

좋은 의견 감사합니다 재성님 ~! 😄
현대적이고 정말 좋은 방법인것 같습니다.

의견 남겨주셔서 위와 같은 경우에 delegate 나 프로토콜을 써야하는 경우가 왜 있을까? 다시 한번 고민해봤는데요. 
2가지 경우는 protocol 을 사용해도 좋을것 같다고 생각이 정리되었습니다.

1. 인터랙션이 다양하고 데이터가 복잡한 경우. 
만약 데이터 업데이트 로직이 복잡하고 인터랙션이 많은 경우 프로토콜로 따로 빼서 cell 이나 detail page 에 대한 명세를 따로 작성하는 것도 좋다고 생각이 들었습니다.

2. Detail 과 List 의 관계가 1:1 이여야 하는 경우.
현재 제가 재직하고 있는 소셜인베스팅랩의 커피하우스는무한스택 형식의 앱이고 FeedCell 이 동시에 여러곳에서 보여지고, FeedDetail 이 여러곳에서 navigate 할수 있습니다. 이런 경우, 하나의 DetailPage 에서 likeStatusPublisher 에 값을 할당할 경우 여러 ListPage 에서 서로 각기 다른 offset 에 해당하는 데이터를 업데이트 해주게 될것 같습니다. delegate 를 통해 parameter 로  받아 데이터를 업데이트하는 것이 유리할것같습니다.

위에 남겨드린 의견에 대해 재성님의 또 다른 의견이나 저의 의견에 대한 피드백 남겨주시면 도움이 될 것같습니다 😄👍

**Comment by x-0o0** [comment]
🫢무한스택이었군요. 왜 delegate를 사용했는지 공감이 되네요! 덕분에 좋은 인풋을 얻어갑니다!👏👏👏
관련해서 새로운 아이디어가 떠오르면 공유드릴게요👍

**Comment by insub4067** [comment]
@jaesung-0o0 좋은 제안 주셔서 덕분에 새로운 인사이트로 생각해 볼 수 있었네요! 즐거웠습니다. 감사합니다 ㅎㅎ
